// <auto-generated />
using System;
using Kukushka.Network.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kukushka.Network.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20210912144220_Add_Users")]
    partial class Add_Users
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("Kukushka.Network.Data.Models.User", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ActivityTime")
                        .HasColumnType("BLOB");

                    b.Property<int>("FreeSpace")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("IP")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Port")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("RsaOpenKey")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Status")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
